# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# switch panes using hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key : command-prompt

# Enable mouse mode (tmux 2.1 and above)
set -g mouse off

# Disable delay when escape in vim
set -sg escape-time 0

# Vi mode
setw -g mode-keys vi

bind-key -T copy-mode-vi q send-keys -X cancel

bind-key -T copy-mode-vi 'J' send-keys -X next-paragraph
bind-key -T copy-mode-vi 'K' send-keys -X previous-paragraph
bind-key -T copy-mode-vi 'E' send-keys -X end-of-line
bind-key -T copy-mode-vi 'B' send-keys -X start-of-line

# Vi select and copy
# bind-key -T copy-mode-vi 'v' send -X begin-selection
# bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

### theme settings ###
# window separators
set-option -wg window-status-separator ""

# monitor window changes
set-option -wg monitor-activity on
set-option -wg monitor-bell on

# set statusbar update interval
set-option -g status-interval 1

### colorscheme ###

# change window screen colors
set-option -wg mode-style bg="#FE8019",fg="#3C3836"

# default statusbar colors (terminal bg should be #282828)
set-option -g status-style bg=terminal,fg="#A89984"

# default window title colors
set-option -wg window-status-style bg="#3C3836",fg="#7C6F64"

# colors for windows with activity
set-option -wg window-status-activity-style bg="#3C3836",fg="#A89984"

# colors for windows with bells
set-option -wg window-status-bell-style bg="#3C3836",fg="#FE8019"

# active window title colors
set-option -wg window-status-current-style bg="#FE8019",fg="#3C3836"

# pane border
set-option -g pane-active-border-style fg="#FE8019"
set-option -g pane-border-style fg="#3C3836"

# message info
set-option -g message-style bg="#FE8019",fg="#3C3836"

# writing commands inactive
set-option -g message-command-style bg="#A89984",fg="#3C3836"

# pane number display
set-option -g display-panes-active-colour "#FE8019"
set-option -g display-panes-colour "#3C3836"

# clock
set-option -wg clock-mode-colour "#FE8019"

# copy mode highlighting
%if #{>=:#{version},3.2}
    set-option -wg copy-mode-match-style "bg=#A89984,fg=#3C3836"
    set-option -wg copy-mode-current-match-style "bg=#FE8019,fg=#3C3836"
%endif

# statusbar formatting
# "#fe8020" MUST be in lowercase here (conflicts with statusline alias otherwise)
set-option -g status-left "#[bg=#fe8019, fg=#282828 bold]#{?client_prefix,#[bg=#b8bb26],#[bg=#fe8019]} [#{session_name}] "
set-option -g status-right "#[bg=#3C3836, fg=#7C6F64] %Y-%m-%d %H:%M:%S #[bg=#A89984, fg=#3C3836 bold]#{?client_prefix,#[bg=#b8bb26],#[bg=#fe8019]} #{host_short} "

set-option -wg window-status-current-format "#[bg=#A89984]#{?window_zoomed_flag,#[fg=#3c3836],#[fg=#3c3836]} #{window_index} #{window_name}* "
set-option -wg window-status-format "#{?window_zoomed_flag,#[fg=default bold],#[fg=default]} #{window_index} #{window_name} "

set-option -as terminal-overrides ",xterm*:RGB"

set -g status-right-length 200
set -g status-left-length 200
