# /Users/scott/.config/tmuxinator/local.yml
name: local
root: ~/

windows:
  - jobs:
      root: ~/Documents/jobs/
  - schools:
      root: ~/Documents/schools/
  - finance:
      root: ~/Documents/finance/
  - misc:
      root: ~/
