# aliases
alias ls='ls -AGFlh'
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -v'
alias mkdir='mkdir -v -p'
alias ln='ln -v'
alias vim='nvim'
alias vimdiff='nvim -d'
alias du='du -h'
alias df='df -h'
